public  class ArithmeticCalculations {
    public void addition(Integer x, Integer y){
        Integer z= x + y;
        system.debug('addition is '+ z);

    }
    public void subtraction (Integer x, Integer y) {
        Integer z= x- y ;
        system.debug('Subtraction is '+z);

    }
    public void multiplication (Integer x, Integer y, Integer m){
        Integer z= x*y*m;
        system.debug('Multiplication is '+z);


    }

    }
    
