public class Cat {
    public string name;
    public string color;
    //we use constructor if we want to execute some apex code asas new instance created.
    //doesnt return anything
    //constructor name is same as class name
    public Cat() {
        system.debug('cat constructor called');
        //we can have multiple cionstructors
        //provide number of parameter or datatype of params are different

    }
    public Cat (string n, string clr){
        name= n;
        color=clr;
        sleeping();
    }
    public void sleeping(){
        system.debug(name + ' is sleeping');
    }
}